// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VanBora.Infrastructure.Data;

#nullable disable

namespace VanBora.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514131930_InitialUsuariosPerfis")]
    partial class InitialUsuariosPerfis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VanBora.Domain.Entities.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid?>("CriadoPorPerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_perfil_id");

                    b.Property<bool?>("Gratuito")
                        .HasColumnType("boolean")
                        .HasColumnName("gratuito");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<decimal?>("TaxaPlataforma")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("taxa_plataforma");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorPerfilId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_perfis_slug")
                        .HasFilter("\"slug\" IS NOT NULL");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_perfis_usuario_id");

                    b.ToTable("perfis", (string)null);
                });

            modelBuilder.Entity("VanBora.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("VanBora.Domain.Entities.Perfil", b =>
                {
                    b.HasOne("VanBora.Domain.Entities.Perfil", "CriadoPorPerfil")
                        .WithMany("MotoristasCriados")
                        .HasForeignKey("CriadoPorPerfilId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VanBora.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Perfis")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("VanBora.Domain.ValueObjects.CNH", "CNH", b1 =>
                        {
                            b1.Property<Guid>("PerfilId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("cnh");

                            b1.HasKey("PerfilId");

                            b1.ToTable("perfis");

                            b1.WithOwner()
                                .HasForeignKey("PerfilId");
                        });

                    b.Navigation("CNH");

                    b.Navigation("CriadoPorPerfil");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VanBora.Domain.Entities.Usuario", b =>
                {
                    b.OwnsOne("VanBora.Domain.ValueObjects.CPF", "CPF", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("cpf");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Valor")
                                .IsUnique()
                                .HasDatabaseName("ix_usuarios_cpf");

                            b1.ToTable("usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("VanBora.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("email");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Valor")
                                .IsUnique()
                                .HasDatabaseName("ix_usuarios_email")
                                .HasFilter("\"email\" IS NOT NULL");

                            b1.ToTable("usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("VanBora.Domain.ValueObjects.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DDD")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("telefone_ddd");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(9)
                                .HasColumnType("character varying(9)")
                                .HasColumnName("telefone_numero");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("CPF")
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("VanBora.Domain.Entities.Perfil", b =>
                {
                    b.Navigation("MotoristasCriados");
                });

            modelBuilder.Entity("VanBora.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Perfis");
                });
#pragma warning restore 612, 618
        }
    }
}
