// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VanBora.Infrastructure.Data;

#nullable disable

namespace VanBora.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520203848_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VanBora.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<string>("ChavePix")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chave_pix");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid?>("CriadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_atualizacao");

                    b.Property<bool?>("Gratuito")
                        .HasColumnType("boolean")
                        .HasColumnName("gratuito");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<decimal?>("TaxaPlataforma")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("taxa_plataforma");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("CriadoPorUsuarioId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_slug")
                        .HasFilter("\"slug\" IS NOT NULL");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("VanBora.Domain.Entities.Van", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ativo");

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer")
                        .HasColumnName("capacidade");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("GerenteUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("gerente_usuario_id");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.HasIndex("GerenteUsuarioId");

                    b.ToTable("vans", (string)null);
                });

            modelBuilder.Entity("VanBora.Domain.Entities.Viagem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_evento");

                    b.Property<DateTime>("DataPartida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_partida");

                    b.Property<Guid>("GerenteUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("gerente_usuario_id");

                    b.Property<string>("LocalEvento")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("local_evento");

                    b.Property<string>("LocalPartida")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("local_partida");

                    b.Property<string>("NomeEvento")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_evento");

                    b.Property<bool>("PossuiIngresso")
                        .HasColumnType("boolean")
                        .HasColumnName("possui_ingresso");

                    b.Property<decimal>("PrecoAssento")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_assento");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("GerenteUsuarioId");

                    b.ToTable("viagens", (string)null);
                });

            modelBuilder.Entity("VanBora.Domain.Entities.ViagemVan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("MotoristaUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("motorista_usuario_id");

                    b.Property<Guid>("VanId")
                        .HasColumnType("uuid")
                        .HasColumnName("van_id");

                    b.Property<Guid>("ViagemId")
                        .HasColumnType("uuid")
                        .HasColumnName("viagem_id");

                    b.HasKey("Id");

                    b.HasIndex("MotoristaUsuarioId");

                    b.HasIndex("VanId");

                    b.HasIndex("ViagemId", "VanId")
                        .IsUnique()
                        .HasDatabaseName("ix_viagem_vans_viagem_id_van_id");

                    b.ToTable("viagem_vans", (string)null);
                });

            modelBuilder.Entity("VanBora.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("VanBora.Domain.Entities.Usuario", "CriadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("VanBora.Domain.ValueObjects.CNH", "CNH", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("cnh");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("VanBora.Domain.ValueObjects.CPF", "CPF", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("cpf");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Valor")
                                .IsUnique()
                                .HasDatabaseName("ix_usuarios_cpf");

                            b1.ToTable("usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("VanBora.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("character varying(254)")
                                .HasColumnName("email");

                            b1.HasKey("UsuarioId");

                            b1.HasIndex("Valor")
                                .IsUnique()
                                .HasDatabaseName("ix_usuarios_email")
                                .HasFilter("\"email\" IS NOT NULL");

                            b1.ToTable("usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.OwnsOne("VanBora.Domain.ValueObjects.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DDD")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("telefone_ddd");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(9)
                                .HasColumnType("character varying(9)")
                                .HasColumnName("telefone_numero");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");
                        });

                    b.Navigation("CNH");

                    b.Navigation("CPF")
                        .IsRequired();

                    b.Navigation("CriadoPorUsuario");

                    b.Navigation("Email");

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("VanBora.Domain.Entities.Van", b =>
                {
                    b.HasOne("VanBora.Domain.Entities.Usuario", "GerenteUsuario")
                        .WithMany()
                        .HasForeignKey("GerenteUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("VanBora.Domain.ValueObjects.Placa", "Placa", b1 =>
                        {
                            b1.Property<Guid>("VanId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("placa");

                            b1.HasKey("VanId");

                            b1.HasIndex("Valor")
                                .IsUnique()
                                .HasDatabaseName("ix_vans_placa");

                            b1.ToTable("vans");

                            b1.WithOwner()
                                .HasForeignKey("VanId");
                        });

                    b.Navigation("GerenteUsuario");

                    b.Navigation("Placa")
                        .IsRequired();
                });

            modelBuilder.Entity("VanBora.Domain.Entities.Viagem", b =>
                {
                    b.HasOne("VanBora.Domain.Entities.Usuario", "GerenteUsuario")
                        .WithMany()
                        .HasForeignKey("GerenteUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GerenteUsuario");
                });

            modelBuilder.Entity("VanBora.Domain.Entities.ViagemVan", b =>
                {
                    b.HasOne("VanBora.Domain.Entities.Usuario", "MotoristaUsuario")
                        .WithMany()
                        .HasForeignKey("MotoristaUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VanBora.Domain.Entities.Van", "Van")
                        .WithMany("ViagemVans")
                        .HasForeignKey("VanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VanBora.Domain.Entities.Viagem", "Viagem")
                        .WithMany("ViagemVans")
                        .HasForeignKey("ViagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MotoristaUsuario");

                    b.Navigation("Van");

                    b.Navigation("Viagem");
                });

            modelBuilder.Entity("VanBora.Domain.Entities.Van", b =>
                {
                    b.Navigation("ViagemVans");
                });

            modelBuilder.Entity("VanBora.Domain.Entities.Viagem", b =>
                {
                    b.Navigation("ViagemVans");
                });
#pragma warning restore 612, 618
        }
    }
}
